// não funciona no IE

document.addEventListener('DOMContentLoaded', () => {
const autores = [
{ label: 'Selecione o autor', value: '', destaque: true },
{ label: 'Marx, Karl', value: 'marx/index.htm' },
{ label: 'Engels, Friedrich', value: 'marx/index.htm' },
{ label: 'Lênin, V. I.', value: 'lenin/index.htm' },
{ label: 'Ordem alfabética', value: 'biblioteca.htm', destaque: true },
{ label: 'Abramo, Fúlvio', value: 'abramo/index.htm' },
{ label: 'Abramowski, Edward Józef', value: 'abramowski/index.htm' },
{ label: 'Adorno, Theodor', value: 'adorno/index.htm' },
{ label: 'Akcelrud, Isaac', value: 'akcelrud/index.htm' },
{ label: 'Alambert, Zuleika', value: 'alambert/index.htm' },
{ label: 'Alberto, Armanda Álvaro', value: 'alberto/index.htm' },
{ label: 'Alencar, Heron', value: 'alencar/index.htm' },
{ label: 'Alessio, Aldo d\'', value: 'alessio/index.htm' },
{ label: 'Alia, Ramiz', value: 'alia/index.htm' },
{ label: 'Allen, James', value: 'allem-james/index.htm' },
{ label: 'Allen, Theodore W.', value: 'allen/index.htm' },
{ label: 'Allende, Salvador', value: 'allende/index.htm' },
{ label: 'Alpatov, Mikhail', value: 'alpatov/index.htm' },
{ label: 'Alquati, Romano', value: 'alquati/index.htm' },
{ label: 'Althusser, Louis', value: 'althusser/index.htm' },
{ label: 'Alves, Mário', value: 'alves/index.htm' },
{ label: 'Amado, Jorge', value: 'amado/index.htm' },
{ label: 'Amazonas, João', value: 'amazonas/index.htm' },
{ label: 'Amendola, Giorgio', value: 'amendola/index.htm' },
{ label: 'Amin, Samir', value: 'amin/index.htm' },
{ label: 'Andropov, Yuri', value: 'andropov/index.htm' },
{ label: 'Angjeli, Kristaq', value: 'angjeli/index.htm' },
{ label: 'Arafat, Yasser', value: 'arafat/index.htm' },
{ label: 'Argan, Giulio Carlo', value: 'argan/index.htm' },
{ label: 'Armand, Émile', value: 'armand-emile/index.htm' },
{ label: 'Armand, Inessa', value: 'armand/index.htm' },
{ label: 'Arroyo, Ângelo', value: 'arroyo/index.htm' },
{ label: 'Arruda, Diógenes', value: 'arruda/index.htm' },
{ label: 'Arshinov, Piotr', value: 'arshinov/index.htm' },
{ label: 'Aveling, Edward', value: 'aveling/index.htm' },
{ label: 'Babeuf, Gracchus', value: 'babeuf/index.htm' },
{ label: 'Babo, Alexandre', value: 'babo/index.htm' },
{ label: 'Badaloni, Nicola', value: 'badaloni/index.htm' },
{ label: 'Ba Jin', value: 'ba-jin/index.htm' },
{ label: 'Bains, Hardial', value: 'bains/index.htm' },
{ label: 'Bakunin, Mikhail', value: 'bakunin/index.htm' },
{ label: 'Baliño, Carlos', value: 'balino/index.htm' },
{ label: 'Bambirra, Vania', value: 'bambirra/index.htm' },
{ label: 'Barata, Agildo', value: 'barata/index.htm' },
{ label: 'Barreto, Lima', value: 'barreto/index.htm' },
{ label: 'Basbaum, Leôncio', value: 'basbaum/index.htm' },
{ label: 'Bayo, Alberto', value: 'bayo/index.htm' },
{ label: 'Bebel, August', value: 'bebel/index.htm' },
{ label: 'Beer, Max', value: 'beer/index.htm' },
{ label: 'Beinstein, Jorge', value: 'beinstein/index.htm' },
{ label: 'Benjamin, Walter', value: 'benjamin/index.htm' },
{ label: 'Bensaid, Daniel', value: 'bensaid/index.htm' },
{ label: 'Beria, Lavrentiy', value: 'beria/index.htm' },
{ label: 'Berkins, Lohana', value: 'berkins/index.htm' },
{ label: 'Berkman, Alexander', value: 'berkman/index.htm' },
{ label: 'Berlinguer, Enrico', value: 'berlinguer/index.htm' },
{ label: 'Berlioz, Joanny', value: 'berlioz/index.htm' },
{ label: 'Bernal, John Desmond', value: 'bernal/index.htm' },
{ label: 'Bernstein, Eduard', value: 'bernstein/index.htm' },
{ label: 'Bettelheim, Charles', value: 'bettelheim/index.htm' },
{ label: 'Bezerra, Gregório', value: 'bezerra/index.htm' },
{ label: 'Bierut, Boleslaw', value: 'bierut/index.htm' },
{ label: 'Blanqui, Louis Auguste', value: 'blanqui/index.htm' },
{ label: 'Bloch, Gérard', value: 'bloch/index.htm' },
{ label: 'Boffa, Giuseppe', value: 'boffa/index.htm' },
{ label: 'Bogdánov, Aleksandr', value: 'bogdanov/index.htm' },
{ label: 'Boldrini, Arrigo', value: 'boldrini/index.htm' },
{ label: 'Bonnet, Marguerite', value: 'bonnet/index.htm' },
{ label: 'Bordiga, Amadeo', value: 'bordiga/index.htm' },
{ label: 'Brandão, Otávio', value: 'brandao/index.htm' },
{ label: 'Brandler, Heinrich', value: 'brandler/index.htm' },
{ label: 'Brar, Harpal', value: 'harnecker/index.htm' },
{ label: 'Brecht, Bertolt', value: 'brecht/index.htm' },
{ label: 'Breitman, George', value: 'breitman/index.htm' },
{ label: 'Brejnév, Leonid', value: 'brezhnev/index.htm' },
{ label: 'Brendel, Cajo', value: 'brendel/index.htm' },
{ label: 'Breton, André', value: 'breton/index.htm' },
{ label: 'Brinton, Maurice', value: 'brinton/index.htm' },
{ label: 'Broué, Pierre', value: 'broue/index.htm' },
{ label: 'Bryant, Louise', value: 'bryant/index.htm' },
{ label: 'Buey, Francisco Fernández', value: 'buey/index.htm' },
{ label: 'Bukharin, Nikolai', value: 'bukharin/index.htm' },
{ label: 'Bulganin, Nikolai', value: 'bulganin/index.htm' },
{ label: 'Buonicore, Augusto', value: 'buonicore/index.htm' },
{ label: 'Burns, Emile', value: 'burns/index.htm' },
{ label: 'Cabral, Amílcar', value: 'cabral/index.htm' },
{ label: 'Campoamor, Clara', value: 'campoamor/index.htm' },
{ label: 'Cannon, James', value: 'cannon/index.htm' },
{ label: 'Caraça, Bento de Jesus', value: 'caraca/index.htm' },
{ label: 'Çarçani, Adil', value: 'carcani/index.htm' },
{ label: 'Carneiro, Edison', value: 'carneiro/index.htm' },
{ label: 'Carone, Edgard', value: 'carone/index.htm' },
{ label: 'Carvalho, Amaro Luiz de (Capivara)', value: 'carvalho-amaro/index.htm' },
{ label: 'Carvalho, Apolônio', value: 'apolonio/index.htm' },
{ label: 'Carpio, Salvador Cayetano', value: 'carpio/index.htm' },
{ label: 'Castro, Fidel', value: 'castro/index.htm' },
{ label: 'Cerroni, Umberto', value: 'cerroni/index.htm' },
{ label: 'Chasin, José', value: 'chasin/index.htm' },
{ label: 'Che Guevara, Ernesto', value: 'guevara/index.htm' },
{ label: 'Chen Boda', value: 'chen-po-ta/index.htm' },
{ label: 'Chen Yun', value: 'chen_yun/index.htm' },
{ label: 'Chtemiénko, Serguei', value: 'chtemenko/index.htm' },
{ label: 'Ciliga, Ante', value: 'ciliga/index.htm' },
{ label: 'Cirules, Enrique', value: 'cirules/index.htm' },
{ label: 'Çobani, Javer', value: 'cobani/index.htm' },
{ label: 'Cohen, Gerald Allan', value: 'cohen/index.htm' },
{ label: 'Connolly, James', value: 'connolly/index.htm' },
{ label: 'Cotrim, Lívia', value: 'cotrim/index.htm' },
{ label: 'Coutinho, Carlos Nelson', value: 'coutinho/index.htm' },
{ label: 'Cruse, Harold', value: 'cruse/index.htm' },
{ label: 'Cueva, Agustín', value: 'cueva/index.htm' },
{ label: 'Cunhal, Álvaro', value: 'cunhal/index.htm' },
{ label: 'Dang Xuan Ky', value: 'dang_xuan_ky/index.htm' },
{ label: 'Dangeville, Roger', value: 'dangeville/index.htm' },
{ label: 'Darcy, Samuel Adams', value: 'darcy/index.htm' },
{ label: 'Dasgupta, Biplab', value: 'dasgupta/index.htm' },
{ label: 'Davydov, Vasili', value: 'davydov/index.htm' },
{ label: 'DeBerry, Clifton', value: 'deberry/index.htm' },
{ label: 'Debord, Guy', value: 'debord/index.htm' },
{ label: 'Deng Xiaoping', value: 'deng-xiaoping/index.htm' },
{ label: 'Dennis, Eugene', value: 'dennis/index.htm' },
{ label: 'Deutscher, Isaac', value: 'deutscher/index.htm' },
{ label: 'Dias, Giocondo', value: 'dias-giocondo/index.htm' },
{ label: 'Dias, Edmundo Fernandes', value: 'dias/index.htm' },
{ label: 'Dimitrov, Georgi', value: 'dimitrov/index.htm' },
{ label: 'Dotres, Merceditas Sánchez', value: 'dotres/index.htm' },
{ label: 'Draper, Hal', value: 'draper/index.htm' },
{ label: 'Du Bois, W. E. B.', value: 'du-bois/index.htm' },
{ label: 'Duclos, Jacques', value: 'duclos/index.htm' },
{ label: 'Dunayevskaya, Raya', value: 'dunayevskaya/index.htm' },
{ label: 'Dune, Eduard', value: 'dune/index.htm' },
{ label: 'Dutt, Rajani Palme', value: 'dutt/index.htm' },
{ label: 'Einstein, Albert', value: 'einstein/index.htm' },
{ label: 'Eisenstein, Serguei', value: 'eisenstein/index.htm' },
{ label: 'Éluard, Paul', value: 'eluard/index.htm' },
{ label: 'Engels, Friedrich', value: 'marx/index.htm' },
{ label: 'Enríquez, Miguel', value: 'enríquez/index.htm' },
{ label: 'Etiévant, Georges', value: 'etievant/index.htm' },
{ label: 'Fabbri, Luigi', value: 'fabbri/index.htm' },
{ label: 'Fabbri, Luce', value: 'fabbri-luce/index.htm' },
{ label: 'Facó, Rui', value: 'faco/index.htm' },
{ label: 'Fajon, Étienne', value: 'fajon/index.htm' },
{ label: 'Fanon, Frantz', value: 'fanon/index.htm' },
{ label: 'Fausto, Ruy', value: 'fausto/index.htm' },
{ label: 'Fernandes, Florestan', value: 'fernandes/index.htm' },
{ label: 'Ferreira, Joaquim Câmara', value: 'ferreira/index.htm' },
{ label: 'Feuerbach, Ludwig', value: 'feuerbach/index.htm' },
{ label: 'Fock, Vladimir', value: 'fock/index.htm' },
{ label: 'Ford, James W.', value: 'ford/index.htm' },
{ label: 'Foster, William Z.', value: 'foster/index.htm' },
{ label: 'Fourier, Charles', value: 'fourier/index.htm' },
{ label: 'Freitas, Alípio', value: 'freitas/index.htm' },
{ label: 'Fréville, Jean', value: 'freville/index.htm' },
{ label: 'Frunze, Mikhail', value: 'frunze/index.htm' },
{ label: 'Furtseva, Yekaterina', value: 'furtseva/index.htm' },
{ label: 'Gagarin, Iuri', value: 'gagarin/index.htm' },
{ label: 'Galeano, Eduardo', value: 'galeano/index.htm' },
{ label: 'Gandhi, Anuradha', value: 'gandhi/index.htm' },
{ label: 'Garroni, Stefano', value: 'garroni/index.htm' },
{ label: 'Gascón, Amparo Poch y', value: 'gascon/index.htm' },
{ label: 'Giap, Vo Nguyen', value: 'giap/index.htm' },
{ label: 'Gika, Comandante', value: 'gika/index.htm' },
{ label: 'Goldman, Emma', value: 'goldman/index.htm' },
{ label: 'Goldner, Loren', value: 'goldner/index.htm' },
{ label: 'Gomułka, Władysław', value: 'gomulka/index.htm' },
{ label: 'Gonçalves, Bento', value: 'goncalves/index.htm' },
{ label: 'Gonçalves, Vasco', value: 'goncalves-vasco/index.htm' },
{ label: 'Gonzalez, Lélia', value: 'gonzalez/index.htm' },
{ label: 'Gorender, Jacob', value: 'gorender/index.htm' },
{ label: 'Gorki, Máximo', value: 'gorki/index.htm' },
{ label: 'Gorter, Herman', value: 'gorter/index.htm' },
{ label: 'Gorz, André', value: 'gorz/index.htm' },
{ label: 'Gossweiler, Kurt', value: 'gossweiler/index.htm' },
{ label: 'Gottwald, Klement', value: 'gottwald/index.htm' },
{ label: 'Grabois, Maurício', value: 'grabois/index.htm' },
{ label: 'Gramsci, Antônio', value: 'gramsci/index.htm' },
{ label: 'Grant, Ted', value: 'grant/index.htm' },
{ label: 'Grave, Jean', value: 'grave/index.htm' },
{ label: 'Grossmann, Henryk', value: 'grossmann/index.htm' },
{ label: 'Grosz, Victor', value: 'grosz/index.htm' },
{ label: 'Guedes, Armênio', value: 'guedes/index.htm' },
{ label: 'Guérin, Daniel', value: 'guerin/index.htm' },
{ label: 'Guha, Moni', value: 'guha/index.htm' },
{ label: 'Guillaume, James', value: 'guillaume/index.htm' },
{ label: 'Guillén, Abraham', value: 'guillen/index.htm' },
{ label: 'Guimarães, Alberto Passos', value: 'guimaraes/index.htm' },
{ label: 'Haldane, J. B. S.', value: 'haldane/index.htm' },
{ label: 'Hallas, Duncan', value: 'hallas/index.htm' },
{ label: 'Hamon, Augustin Frédéric', value: 'hamon/index.htm' },
{ label: 'Hampton, Fred', value: 'hampton/index.htm' },
{ label: 'Handal, Schafik', value: 'handal/index.htm' },
{ label: 'Harman, Chris', value: 'harman/index.htm' },
{ label: 'Harnecker, Marta', value: 'harnecker/index.htm' },
{ label: 'Harpal, Brar', value: 'harnecker/index.htm' },
{ label: 'Haywood, Harry', value: 'haywood/index.htm' },
{ label: 'Hegel, Georg', value: 'hegel/index.htm' },
{ label: 'Heijenoort, Jean Van', value: 'heijenoort/index.htm' },
{ label: 'Hekmat, Mansoor', value: 'hekmat/index.htm' },
{ label: 'Ho Chi Minh', value: 'ho_chi_minh/index.htm' },
{ label: 'Hobsbawm, Eric', value: 'hobsbawm/index.htm' },
{ label: 'Holzkamp, Klaus', value: 'holzkamp/index.htm' },
{ label: 'Horkheimer, Max', value: 'horkheimer/index.htm' },
{ label: 'Houtart, François', value: 'houtart/index.htm' },
{ label: 'Hoxha, Enver', value: 'hoxha/index.htm' },
{ label: 'Hoxha, Nexhmije', value: 'hoxha_nex/index.htm' },
{ label: 'Hughes, Langston', value: 'hughes/index.htm' },
{ label: 'Hu Qiaomu', value: 'hu-qiaomu/index.htm' },
{ label: 'Ianni, Octavio', value: 'ianni/index.htm' },
{ label: 'Iaroslavski, Emilian', value: 'iaroslavski/index.htm' },
{ label: 'Ibarruri, Dolores', value: 'ibarruri/index.htm' },
{ label: 'Ilienkov, Evald Vasiliévitch', value: 'ilyenkov/index.htm' },
{ label: 'Inglez, Carlos Aboim', value: 'inglez/index.htm' },
{ label: 'Ingrao, Pietro', value: 'ingrao/index.htm' },
{ label: 'James, C. L. R.', value: 'james/index.htm' },
{ label: 'Jiang Zemin', value: 'jiang_zemin/index.htm' },
{ label: 'Joffe, Adolph', value: 'joffe/index.htm' },
{ label: 'Jones, Claudia', value: 'jones/index.htm' },
{ label: 'Julião, Francisco', value: 'juliao/index.htm' },
{ label: 'Júnior, Caio Prado', value: 'junior/index.htm' },
{ label: 'Jurandir, Dalcídio', value: 'jurandir/index.htm' },
{ label: 'Kadaré, Ismail', value: 'kadare/index.htm' },
{ label: 'Kaganovitch, Lazar', value: 'kaganovitch/index.htm' },
{ label: 'Kalinin, Mikhail', value: 'kalinin/index.htm' },
{ label: 'Kant, Immanuel', value: 'kant/index.htm' },
{ label: 'Kardelj, Edvard', value: 'kardelj/index.htm' },
{ label: 'Kautsky, Karl', value: 'kautsky/index.htm' },
{ label: 'Keynes, John Maynard', value: 'keynes/index.htm' },
{ label: 'Khabarova, Tatyana Mikhailovna', value: 'khabarova/index.htm' },
{ label: 'Khrushchov, Nikita', value: 'khrushchev/index.htm' },
{ label: 'Kim Il Sung', value: 'kim_il_sung/index.htm' },
{ label: 'Kim Jong Il', value: 'kim_jong-il/index.htm' },
{ label: 'Kirichenko, Alexei', value: 'kirichenko/index.htm' },
{ label: 'Kollontai, Alexandra', value: 'kollontai/index.htm' },
{ label: 'Kolman, Ernst', value: 'kolman/index.htm' },
{ label: 'Konder, Leandro', value: 'konder/index.htm' },
{ label: 'Kopriva, Ladislav', value: 'kopriva/index.htm' },
{ label: 'Korsch, Karl', value: 'korsch/index.htm' },
{ label: 'Kosik, Karel', value: 'kosik/index.htm' },
{ label: 'Kremer, Arkadi', value: 'kremer/index.htm' },
{ label: 'Kropotkin, Piotr', value: 'kropotkin/index.htm' },
{ label: 'Krupskaia, Nadejda', value: 'krupskaia/index.htm' },
{ label: 'Kurz, Robert', value: 'kurz/index.htm' },
{ label: 'Kuusinen, Otto', value: 'kuusinen/index.htm' },
{ label: 'Labica, Georges', value: 'labica/index.htm' },
{ label: 'Lacerda, Fernando', value: 'lacerda/index.htm' },
{ label: 'Lafargue, Paul', value: 'lafargue/index.htm' },
{ label: 'Lamarca, Carlos', value: 'lamarca/index.htm' },
{ label: 'Lambert, Pierre', value: 'lambert/index.htm' },
{ label: 'Landauer, Gustav', value: 'landauer/index.htm' },
{ label: 'Langevin, Paul', value: 'langevin/index.htm' },
{ label: 'Lanti, Eugène', value: 'lanti/index.htm' },
{ label: 'Lapidus, Iosif', value: 'lapidus/index.htm' },
{ label: 'Lavigne, Eusínio Gaston', value: 'lavigne/index.htm' },
{ label: 'Leacock, Eleanor Burke', value: 'leacock/index.htm' },
{ label: 'Leduc, Victor', value: 'leduc/index.htm' },
{ label: 'Lehning, Arthur', value: 'lehning/index.htm' },
{ label: 'Leibiniz, Gottfried Wilhelm', value: 'leibniz/index.htm' },
{ label: 'Lênin, V. I.', value: 'lenin/index.htm' },
{ label: 'Leon, Daniel de', value: 'deleon/index.htm' },
{ label: 'Leontiev, Alexei', value: 'leontiev/index.htm' },
{ label: 'Leuenroth, Edgard', value: 'leuenroth/index.htm' },
{ label: 'Levins, Richard', value: 'levins/index.htm' },
{ label: 'Lewin, Moshe', value: 'lewin/index.htm' },
{ label: 'Li Dazhao', value: 'li-dazhao/index.htm' },
{ label: 'Liebknecht, Karl', value: 'liebknecht/index.htm' },
{ label: 'Lifschits, Mikhail', value: 'lifschits/index.htm' },
{ label: 'Lima, José Inácio de Abreu e', value: 'lima-abreu/index.htm' },
{ label: 'Lisboa, Manoel', value: 'lisboa/index.htm' },
{ label: 'Liu Chao-Tsi', value: 'liu-chao-tsi/index.htm' },
{ label: 'Lora, Guillermo', value: 'lora/index.htm' },
{ label: 'Losurdo, Domenico', value: 'losurdo/index.htm' },
{ label: 'Lozovski, Alexandr', value: 'lozovski/index.htm' },
{ label: 'Lu Ting-Yi', value: 'lu-ting-yi/index.htm' },
{ label: 'Ludwig, Emil', value: 'ludwig/index.htm' },
{ label: 'Lukács, György', value: 'lukacs/index.htm' },
{ label: 'Lunatchárski, Anatoli', value: 'lunatcharski/index.htm' },
{ label: 'Luppol, Ivan', value: 'kapitonovich/index.htm' },
{ label: 'Luria, Alexander', value: 'luria/index.htm' },
{ label: 'Luso Soares, Fernando', value: 'luso/index.htm' },
{ label: 'Luxemburgo, Rosa', value: 'luxemburgo/index.htm' },
{ label: 'Lu Xun', value: 'lu-xun/index.htm' },
{ label: 'Machajski, Jan Waclaw', value: 'machajski/index.htm' },
{ label: 'Machel, Josina', value: 'machel-josina/index.htm' },
{ label: 'Machel, Samora', value: 'machel/index.htm' },
{ label: 'Magdoff, Harry Samuel', value: 'magdoff/index.htm' },
{ label: 'Makarenko, Anton S.', value: 'makarenko/index.htm' },
{ label: 'Makhno, Nestor', value: 'makhno/index.htm' },
{ label: 'Maksimóvski, Vladímir', value: 'maksimovski/index.htm' },
{ label: 'Malatesta, Errico', value: 'malatesta/index.htm' },
{ label: 'Malenkov, Gueórgui', value: 'malenkov/index.htm' },
{ label: 'Malina, Salomão', value: 'malina/index.htm' },
{ label: 'Malyshev, Sergei', value: 'malyshev/index.htm' },
{ label: 'Manfred, Albert', value: 'manfred/index.htm' },
{ label: 'Mandel, Ernest', value: 'mandel/index.htm' },
{ label: 'Manuilsky, Dmitri', value: 'manuilsky/index.htm' },
{ label: 'Mao Zedong', value: 'mao/index.htm' },
{ label: 'Marchais, George', value: 'marchais/index.htm' },
{ label: 'Marcuse, Herbert', value: 'marcuse/index.htm' },
{ label: 'Mariátegui, José Carlos', value: 'mariategui/index.htm' },
{ label: 'Marighella, Carlos', value: 'marighella/index.htm' },
{ label: 'Marini, Ruy Mauro', value: 'marini/index.htm' },
{ label: 'Martens, Ludo', value: 'martens/index.htm' },
{ label: 'Martov, Júlio', value: 'martov/index.htm' },
{ label: 'Marty, André', value: 'marty/index.htm' },
{ label: 'Marx, Eleanor', value: 'eleanor/index.htm' },
{ label: 'Marx, Jenny', value: 'jenny/index.htm' },
{ label: 'Marx, Karl', value: 'marx/index.htm' },
{ label: 'Marxhausen, Thomas', value: 'marxhausen/index.htm' },
{ label: 'Marquit, Erwin', value: 'marquit/index.htm' },
{ label: 'Mattick, Paul', value: 'mattick/index.htm' },
{ label: 'Maximoff, Grigori', value: 'maximoff/index.htm' },
{ label: 'Mayakovsky, Vladimir', value: 'mayakovsky/index.htm' },
{ label: 'Mazumdar, Charu', value: 'mazundar/index.htm' },
{ label: 'Medeiros, António Tomás', value: 'medeiros/index.htm' },
{ label: 'Mehring, Franz', value: 'mehring/index.htm' },
{ label: 'Mella, Julio Antonio', value: 'mella-julio/index.htm' },
{ label: 'Mella, Ricardo', value: 'mella/index.htm' },
{ label: 'Mészáros, István', value: 'meszaros/index.htm' },
{ label: 'Messali Hadj, Ahmed', value: 'messali-hadj/index.htm' },
{ label: 'Mett, Ida', value: 'mett/index.htm' },
{ label: 'Meyer, Ernest', value: 'meyer_ernest/index.htm' },
{ label: 'Meyer, Victor', value: 'meyer/index.htm' },
{ label: 'Miasnikov, Gavril Ilyich', value: 'miasnikov/index.htm' },
{ label: 'Mikhailov, Nikolai', value: 'mikhailov/index.htm' },
{ label: 'Mikoian, Anastas', value: 'mikoian/index.htm' },
{ label: 'Molotov, Vyacheslav', value: 'molotov/index.htm' },
{ label: 'Monmousseau, Gaston', value: 'monmousseau/index.htm' },
{ label: 'Montefiore, Dora', value: 'montefiore/index.htm' },
{ label: 'Montenegro, Ana', value: 'montenegro/index.htm' },
{ label: 'Morais, Clodomir', value: 'morais/index.htm' },
{ label: 'Moreno, Nahuel', value: 'moreno/index.htm' },
{ label: 'Moura, Clóvis', value: 'moura/index.htm' },
{ label: 'Moura, Maria Lacerda de', value: 'moura-maria/index.htm' },
{ label: 'Napoleoni, Cláudio', value: 'napoleoni/index.htm' },
{ label: 'Neto, Agostinho', value: 'neto/index.htm' },
{ label: 'Newton, Huey', value: 'newton/index.htm' },
{ label: 'Nietzsche, Friedrich', value: 'nietzsche/index.htm' },
{ label: 'Nin, Andreu', value: 'nin/index.htm' },
{ label: 'Nkrumah, Kwame', value: 'nkrumah/index.htm' },
{ label: 'Novack, George', value: 'novack/index.htm' }, 
{ label: 'Oliveira, César', value: 'oliveira/index.htm' },
{ label: 'Ódena, Elena', value: 'odena/index.htm' },
{ label: 'Oliveira, Francisco de', value: 'oliveira-chico/index.htm' },
{ label: 'Ossinski, Nikolai', value: 'ossinski/index.htm' }, 
{ label: 'Ostrovitianov, Konstantín', value: 'ostrovitianov/index.htm' },
{ label: 'Padmore, George', value: 'padmore/index.htm' },
{ label: 'Pajetta, Giancarlo', value: 'pajetta/index.htm' }, 
{ label: 'Pankhurst, Sylvia', value: 'pankhurst/index.htm' }, 
{ label: 'Pankratova, Anna Mikhailovna', value: 'pankratova/index.htm' }, 
{ label: 'Pannekoek, Anton', value: 'pannekoe/index.htm' },
{ label: 'Panzieri, Raniero', value: 'panzieri/index.htm' },
{ label: 'Parsons, Lucy', value: 'parsons/index.htm' },
{ label: 'Pashukanis, Evgeny', value: 'pashukanis/index.htm' },
{ label: 'Pavlov, Ivan', value: 'pavlov/index.htm' },
{ label: 'Pêcheux, Michel', value: 'pecheux/index.htm' },
{ label: 'Pelloutier, Fernand', value: 'pelloutier/index.htm' },
{ label: 'Peñaranda, Agar', value: 'penaranda/index.htm' },
{ label: 'Pereira, Astrojildo', value: 'astrojildo/index.htm' },
{ label: 'Perlman, Fredy', value: 'perlman/index.htm' },
{ label: 'Petrichenko, Stepan', value: 'petrichenko/index.htm' },
{ label: 'Pervukhin, Mikhail', value: 'pervukhin/index.htm' },
{ label: 'Pfemfert, Franz', value: 'pfemfert/index.htm' },
{ label: 'Piatnitsky, Ossip', value: 'piatnitsky/index.htm' },
{ label: 'Pieck, Wilhelm', value: 'pieck/index.htm' },
{ label: 'Pinto, Álvaro Vieira', value: 'pinto/index.htm' },
{ label: 'Plekhanov, Guiorgui', value: 'plekhanov/index.htm' },
{ label: 'Pokrovsky, Mikhail', value: 'pokrovsky/index.htm' },
{ label: 'Politzer, Georges', value: 'politzer/index.htm' },
{ label: 'Poltorak, Arkady', value: 'poltorak/index.htm' },
{ label: 'Pomar, Pedro', value: 'pomar/index.htm' },
{ label: 'Pomar, Wladimir', value: 'pomar-wladimir/index.htm' },
{ label: 'Pospelov, Pyotr', value: 'pospelov/index.htm' },
{ label: 'Postone, Moishe', value: 'postone/index.htm' },
{ label: 'Pouget, Emile', value: 'pouget/index.htm' },
{ label: 'Poulantzas, Nicos', value: 'poulantzas/index.htm' },
{ label: 'Preobrazhensky, Evgeni', value: 'preobrazhensky/index.htm' },
{ label: 'Prestes, Luiz Carlos', value: 'prestes/index.htm' },
{ label: 'Prestes, Olga Benário', value: 'prestes-olga/index.htm' },
{ label: 'Proudhon, Pierre-Joseph', value: 'proudhon/index.htm' },
{ label: 'Queiroz, Eça de', value: 'queiroz-eca/index.htm' },
{ label: 'Queiroz, Maurício Vinhas de', value: 'queiroz/index.htm' },
{ label: 'Quental, Antero de', value: 'quental/index.htm' },
{ label: 'Quijano, Anibal', value: 'quijano/index.htm' },
{ label: 'Quirós, Manuel', value: 'quiros/index.htm' },
{ label: 'Radek, Karl', value: 'radek/index.htm' },
{ label: 'Ragionieri, Ernesto', value: 'ragionieri/index.htm' },
{ label: 'Rakosi, Mathias', value: 'rakosi/index.htm' },
{ label: 'Rakovski, Christian', value: 'rakovski/index.htm' },
{ label: 'Ramette, Arthur', value: 'ramette/index.htm' },
{ label: 'Ramos, Graciliano', value: 'graciliano/index.htm' },
{ label: 'Ramos, Jorge Abelardo', value: 'ramos/index.htm' },
{ label: 'Raposo, Manuel Coelho', value: 'raposo/index.htm' },
{ label: 'Rappoport, Charles', value: 'rappoport/index.htm' },
{ label: 'Rates, José Carlos', value: 'rates/index.htm' },
{ label: 'Reale, Eugenio', value: 'reale/index.htm' },
{ label: 'Reclus, Élisée', value: 'reclus/index.htm' },
{ label: 'Reed, John', value: 'reed/index.htm' },
{ label: 'Reed, Evelyn', value: 'reed-evelyn/index.htm' },
{ label: 'Reis, Dinarco', value: 'reis/index.htm' },
{ label: 'Reiss, Ignace', value: 'reiss/index.htm' },
{ label: 'Rezk, Antonio', value: 'rezk/index.htm' },
{ label: 'Riazanov, David', value: 'riazanov/index.htm' },
{ label: 'Ricardo, David', value: 'ricardo/index.htm' },
{ label: 'Rocker, Rudolf', value: 'rocker/index.htm' },
{ label: 'Rodney, Walter', value: 'rodney/index.htm' },
{ label: 'Rodrigues, Edgar', value: 'rodrigues_edgar/index.htm' },
{ label: 'Rodrigues, Francisco Martins', value: 'rodrigues/index.htm' },
{ label: 'Rodrigues, Miguel Urbano', value: 'rodrigues-miguel/index.htm' },
{ label: 'Romeu, Xavier', value: 'romeu/index.htm' },
{ label: 'Rosdolsky, Roman', value: 'rosdolsky/index.htm' },
{ label: 'Roy, Manabendra Nath', value: 'roy/index.htm' },
{ label: 'Rubel, Maximilien', value: 'rubel/index.htm' },
{ label: 'Rubinstein, Serguei', value: 'rubinstein/index.htm' },
{ label: 'R&uuml;hle, Otto', value: 'ruhle/index.htm' },
{ label: 'Ruy, José Carlos', value: 'ruy/index.htm' },
{ label: 'Saburov, Maxim', value: 'saburov/index.htm' },
{ label: 'Sacchetta, Hermínio', value: 'sachetta/index.htm' },
{ label: 'Sachs, Érico Czaczkes', value: 'sachs/index.htm' },
{ label: 'Sader, Eder Simão', value: 'sader/index.htm' },
{ label: 'Saffioti, Heleieth', value: 'saffioti/index.htm' },
{ label: 'Sankara, Thomas', value: 'sankara/index.htm' },
{ label: 'Santos, Aurélio', value: 'santos/index.htm' },
{ label: 'Santos, Theotônio dos', value: 'santos-theotonio/index.htm' },
{ label: 'Saprónov, Timofei', value: 'sapronov/index.htm' },
{ label: 'Saramago, José', value: 'saramago/index.htm' },
{ label: 'Sartre, Jean-Paul', value: 'sartre/index.htm' },
{ label: 'Schaff, Adam', value: 'schaff/index.htm' },
{ label: 'Schapiro, Alexander', value: 'schapiro/index.htm' },
{ label: 'Schwitzguébel, Adhémar', value: 'schwitzguebel/index.htm' },
{ label: 'Secchia, Pietro', value: 'secchia/index.htm' },
{ label: 'Serge, Victor', value: 'serge/index.htm' },
{ label: 'Sertório, Manuel', value: 'sertorio/index.htm' },
{ label: 'Sève, Lucien', value: 'seve/index.htm' },
{ label: 'Shepilov, Dmitri', value: 'shepilov/index.htm' },
{ label: 'Shliapnikov, Alexander', value: 'shliapnikov/index.htm' },
{ label: 'Sinani, Georgy Borisovich Skalov', value: 'sinani/index.htm' },
{ label: 'Slánsky, Rudolf', value: 'slansky/index.htm' },
{ label: 'Smith, Adam', value: 'smith/index.htm' },
{ label: 'Soares, Pedro', value: 'soares/index.htm' },
{ label: 'Sodré, Nélson Werneck', value: 'sodre/index.htm' },
{ label: 'Sohn-Rethel, Alfred', value: 'sohn-rethel/index.htm' },
{ label: 'Souvarine, Boris', value: 'souvarine/index.htm' },
{ label: 'Spilimbergo, Jorge Enea', value: 'spilimbergo/index.htm' },
{ label: 'Stalin, Josef', value: 'stalin/index.htm' },
{ label: 'Starobin, Joseph Robert', value: 'starobin/index.htm' },
{ label: 'Strasser, Josef', value: 'strasser/index.htm' },
{ label: 'Struik, Dirk Jan', value: 'struik/index.htm' },
{ label: 'Suchodolski, Bogdan', value: 'suchodolski/index.htm' },
{ label: 'Sultan-Galiev, Mirsaid', value: 'sultan-galiev/index.htm' },
{ label: 'Sun Yat Sen', value: 'sun-yat-sen/index.htm' },
{ label: 'Surjeet, Harkishan Singh', value: 'surjeet/index.htm' },
{ label: 'Suslov, Mikhail', value: 'suslov/index.htm' },
{ label: 'Sweezy, Paul', value: 'sweezy/index.htm' },
{ label: 'Ta Thu Thau', value: 'ta/index.htm' },
{ label: 'Tchakhotine, Sergei', value: 'tchakhotine/index.htm' },
{ label: 'Thalheimer, August', value: 'thalheimer/index.htm' },
{ label: 'Thompson, Edward Palmer', value: 'thompson/index.htm' },
{ label: 'Thorez, Maurice', value: 'thorez/index.htm' },
{ label: 'Tito, Josip Broz', value: 'tito/index.htm' },
{ label: 'Togliatti, Palmiro', value: 'togliatti/index.htm' },
{ label: 'Trachtenberg, Orest', value: 'trachtenberg/index.htm' },
{ label: 'Tragtenberg, Maurício', value: 'tragtenberg/index.htm' },
{ label: 'Tristan, Flora', value: 'tristan/index.htm' },
{ label: 'Trường Chinh', value: 'truong-chinh/index.htm' },
{ label: 'Trotsky, Leon', value: 'trotsky/index.htm' },
{ label: 'Trotsky, Natalia', value: 'sedova/index.htm' },
{ label: 'Varga, Eugéne', value: 'varga/index.htm' },
{ label: 'Vasco, Neno', value: 'vasco/index.htm' },
{ label: 'Vázquez, Adolfo Sánchez', value: 'vazquez/index.htm' },
{ label: 'Vieira, Alexandre Fernandes', value: 'vieira/index.htm' },
{ label: 'Volin, Vsevolod', value: 'volin/index.htm' },
{ label: 'Voloshinov, Valentin', value: 'voloshinov/index.htm' },
{ label: 'Vorochilov, Kliment', value: 'vorochilov/index.htm' },
{ label: 'Voronsky, Aleksandr', value: 'voronsky/index.htm' },
{ label: 'Vygotsky, Lev', value: 'vygotsky/index.htm' },
{ label: 'Xholi, Zija', value: 'xholi/index.htm' },
{ label: 'Wagner, Helmut', value: 'wagner/index.htm' },
{ label: 'Wallon, Henri', value: 'wallon/index.htm' },
{ label: 'Weber, Max', value: 'weber/index.htm' },
{ label: 'Weinstone, William Wolf', value: 'weinstone/index.htm' },
{ label: 'Whyte, Harry', value: 'whyte/index.htm' },
{ label: 'Willard, Marcel', value: 'willard/index.htm' },
{ label: 'Wood, Ellen Meiksins', value: 'wood/index.htm' },
{ label: 'Wright, John', value: 'wright/index.htm' },
{ label: 'Yakovlev, Nikolai', value: 'yakovlev/index.htm' },
{ label: 'Yanovskaya, Sofia', value: 'yanovskaya/index.htm' },
{ label: 'Yao Wenyuan', value: 'yao-wenyuan/index.htm' },
{ label: 'Zetkin, Clara', value: 'zetkin/index.htm' },
{ label: 'Zhang Chunqiao', value: 'zhang/index.htm' },
{ label: 'Zhdanov, Andrei', value: 'zhdanov/index.htm' },
{ label: 'Zhou Enlai', value: 'chu-en-lai/index.htm' },
{ label: 'Zinoviev, Aleksandr', value: 'zinoviev-alexandr/index.htm' },
{ label: 'Zinoviev, Grigori', value: 'zinoviev/index.htm' },
{ label: 'Zo d\'Axa', value: 'zo-daxa/index.htm' }
];

const secoes = [
{ label: 'ou selecione a seção', value: '', destaque: true },
{ label: 'Biblioteca', value: 'biblioteca.htm' },
{ label: 'Dicionário', value: 'dicionario/index.htm' },
{ label: 'Novidades', value: 'admin/novidades.htm' },
{ label: 'Outros idiomas', value: '../xlang/index.htm' },
{ label: 'Seções temáticas', value: 'tematica/index.htm', destaque: true },
{ label: 'Álbum de imagens', value: 'tematica/album_fotos/index.htm' },
{ label: 'Audiolivros', value: 'tematica/audiolivros.htm' },
{ label: 'Cinema e revolução', value: 'tematica/filmes/index.htm' },
{ label: 'Coleção de eBooks', value: 'ebooks/index.htm' },
{ label: 'Ditadura civil-militar de 1964', value: 'tematica/ditadura1964.htm' },
{ label: 'Documentos históricos', value: 'tematica/documentos.htm' },
{ label: 'Documentos da Frelimo', value: 'tematica/frelimo.htm' },
{ label: 'Fascismo', value: 'tematica/fascismo.htm' },
{ label: 'Imprensa proletária', value: 'tematica/imprensa.htm' },
{ label: 'Luta armada', value: 'tematica/luta-armada.htm' },
{ label: 'Marxismo e a mulher', value: 'tematica/mulher.htm' },
{ label: 'Marxismo e a arte', value: 'tematica/arte.htm' },
{ label: 'Marxismo e a questão racial', value: 'tematica/racismo.htm' },
{ label: 'Marxismo e religião', value: 'tematica/religiao.htm' },
{ label: 'Marxismo, gênero e sexualidade', value: 'tematica/lgbt.htm' },
{ label: 'Música revolucionária', value: 'tematica/musica/index.htm' },
{ label: 'Partidos comunistas', value: 'tematica/partidos.htm' },
{ label: 'Questão agrária', value: 'tematica/questao-agraria.htm' },
{ label: 'Questão palestina', value: 'tematica/palestina.htm' },
{ label: 'Repressão política', value: 'tematica/repressao.htm' },
{ label: 'Revolução dos Cravos', value: 'tematica/25abril.htm' },
{ label: 'Revolução Russa', value: 'tematica/revolucao_1917.htm' },
{ label: 'Sindicalismo', value: 'tematica/sindicalismo.htm' },
{ label: 'Outras páginas', value: '', destaque: true },
{ label: 'Quem somos', value: '../admin/volunteers/steering.htm' },
{ label: 'Mapa do site', value: 'admin/mapa.htm' }
];

const menuContainer = document.getElementById('menu-container');

const createSelect = (options, labelText) => {
const form = document.createElement('form');
const select = document.createElement('select');
select.setAttribute('aria-label', labelText);

options.forEach(opt => {
const option = document.createElement('option');
option.value = opt.value;
option.textContent = opt.label;
if (opt.destaque) {
option.classList.add('destaque');
}
select.appendChild(option);
});

select.addEventListener('change', () => {
if (select.value) {
window.location.href = select.value;
}
});

form.appendChild(select);
return form;
};

const table = document.createElement('table');

const row1 = table.insertRow();
const cell1 = row1.insertCell();
cell1.appendChild(createSelect(autores, 'Selecione um autor'));

const row2 = table.insertRow();
const cell2 = row2.insertCell();
cell2.appendChild(createSelect(secoes, 'Ou selecione uma seção'));

menuContainer.appendChild(table);
});
